### PR TITLE
Fix clang build failure

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Thanks. I think this needs to also be fixed in the cmake, I thought the
failure was there.

**Comment by isuruf** [comment]
Yes, I added it in the new commit

**Comment by certik** [comment]
I think this is the right fix --- however, I also think the changes in https://github.com/sympy/symengine/pull/484 will take care of this. I am going to keep this PR open for now. Because let's face it, adding `-D__extern_always_inline=inline` is just a hack, and the true solution is to use libc++ with clang, which is well supported.

**Comment by isuruf** [comment]
Yes, it is a hack. It's fixed in latest clang, but you need to fix it for old clang versions like in Ubuntu 12.04 (which is used in travis). Installing libc++ in Ubuntu 12.04 is a complicated task and it doesn't fix it.

**Comment by certik** [comment]
I think this PR doesn't fix all the failures with clang that we are having. We need to figure out how to fix all the problems.

**Pull request closed without merging**
